version: '3'
services:
  web:
    build:
      context: docker/nginx
      args:
        - APP_NAME=${APP_NAME}
    volumes:
      - ./docker/nginx/conf/app.conf.template:/etc/nginx/conf.d/app.conf.template
      - ./backend/:/var/www/${APP_NAME}/
    ports:
      - ${INCOME_PORT}:80
    restart: always
    depends_on:
      - php
      - db
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    container_name: ${APP_NAME}_php
    restart: always
    volumes:
      - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./backend/:/var/www/${APP_NAME}/
  composer:
    image: composer
    volumes:
      - ./backend:/app
    command: install
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/
